'use client';
import Link from 'next/link';
import { nowLocal, SOURCES, STORES, uid, type Lead } from '@/lib/marketing/local';
import { button, card, dateLabel, Field, input, money, primary, useMarketing } from './marketing-shared';
import { LeadActions } from './marketing-lead-actions';
export function MarketingProfile({ userId, leadId }: { userId: string; leadId: string }) {
  const { data, save, message, setMessage } = useMarketing(userId);
  if (!data) return <p className="p-8" role="status">{message || 'Loading customer profile…'}</p>;
  const lead = data.leads.find(l => l.id === leadId);
  if (!lead) return <div className="p-8 text-ink"><h1 className="text-xl font-semibold">Lead not found in this browser</h1><Link className={`${button} mt-4`} href="/marketing">Back to Marketing</Link></div>;
  const update = (next: Lead) => { const ok = save({ ...data, leads: data.leads.map(l => l.id === lead.id ? next : l) }); if (ok) setMessage('Profile saved locally.'); return ok; };
  const sales = data.sales.filter(s => s.phone === lead.phone);
  const timeline = [...lead.interactions.map(i => ({ id: i.id, at: i.at, title: i.outcome ?? i.type, text: i.text })), ...sales.map(s => ({ id: `sale-${s.invoice}`, at: s.date, title: 'Purchase', text: `${s.invoice} · ${s.amount === null ? 'Amount not recorded' : money(s.amount)} · ${s.store || 'Store not recorded'}` }))].sort((a, b) => b.at.localeCompare(a.at));
  return <main className="mx-auto max-w-[92rem] space-y-6 px-4 py-8 sm:px-6 lg:px-8">
    <Link href="/marketing" className="text-sm text-accent">← Marketing workspace</Link>
    <header><p className="text-xs uppercase tracking-widest text-ink-muted">Customer profile · Local</p><h1 className="mt-2 text-3xl font-semibold text-ink">{lead.name}</h1><p className="mt-2 break-all text-sm text-ink-2">{lead.id} · {lead.phone}</p></header>
    <LeadActions key={lead.id} lead={lead} update={update} />
    {message && <p role="status" className={`${card} text-sm text-ink`}>{message}</p>}
    <div className="grid gap-3 sm:grid-cols-4">{[['Lifetime sales', money(sales.reduce((n, s) => n + (s.amount ?? 0), 0))], ['Orders', String(sales.length)], ['Last purchase', dateLabel(sales.map(s => s.date).filter(Boolean).sort().at(-1) ?? '')], ['Preferred store', lead.preferredStore || 'Not recorded']].map(([label, value]) => <div className={card} key={label}><p className="text-xs text-ink-muted">{label}</p><p className="mt-2 text-xl font-semibold text-ink">{value}</p></div>)}</div>
    <div className="grid items-start gap-6 lg:grid-cols-2"><div className="space-y-6">
      <form key={lead.id + lead.email + lead.city} className={`${card} space-y-4`} onSubmit={e => { e.preventDefault(); const f = new FormData(e.currentTarget); const get = (k: string) => String(f.get(k) ?? '').trim(); update({ ...lead, name: get('name'), email: get('email'), city: get('city'), preferredStore: get('store'), interactions: [...lead.interactions, { id: uid(), at: nowLocal(), type: 'profile', text: 'Contact details updated.' }] }); }}>
        <h2 className="text-lg font-semibold text-ink">Contact & preferences</h2><Field label="Name"><input name="name" required defaultValue={lead.name} className={input} /></Field><Field label="Contact number · identity key"><input readOnly value={lead.phone} className={input} /></Field><Field label="Email"><input type="email" name="email" defaultValue={lead.email} className={input} /></Field><Field label="City"><input name="city" defaultValue={lead.city} className={input} /></Field><Field label="Preferred store"><select name="store" defaultValue={lead.preferredStore} className={input}><option value="">Not recorded</option>{STORES.map(s => <option key={s}>{s}</option>)}</select></Field><button className={primary}>Save profile</button>
      </form>
      <section className={card}><h2 className="text-lg font-semibold text-ink">Intent & calling</h2><dl className="mt-4 grid grid-cols-2 gap-3 text-sm text-ink-2">{[['Call outcome', lead.status], ['Intent', lead.intent], ['Product', lead.product], ['Category', lead.category]].map(([k, v]) => <div key={k}><dt className="text-xs text-ink-muted">{k}</dt><dd className="mt-1">{v || 'Not recorded'}</dd></div>)}</dl></section>
      <section className={card}><h2 className="text-lg font-semibold text-ink">Acquisition history</h2><p className="mt-1 text-xs text-ink-muted">Date-Time: {dateLabel(lead.acquiredAt)} · all times IST</p><div className="mt-4 space-y-3">{lead.acquisitions.map((a, i) => <div key={i} className="rounded-lg bg-inset p-3 text-sm text-ink"><p className="font-medium">{a.source} · {a.campaignId || 'No campaign recorded'}</p><p className="mt-1 text-ink-2">{dateLabel(a.at)} · Cost per lead: {a.cost === null ? 'Not available' : money(a.cost)}</p></div>)}</div>
        <form className="mt-5 space-y-3 border-t border-line pt-4" onSubmit={e => { e.preventDefault(); const form = e.currentTarget; const f = new FormData(form); const source = String(f.get('source')); const campaignId = String(f.get('campaign') ?? '').trim(); const cost = f.get('cost') ? Number(f.get('cost')) : null; const at = nowLocal(); if (update({ ...lead, acquisitions: [...lead.acquisitions, { source, campaignId, at, cost }], interactions: [...lead.interactions, { id: uid(), at, type: 'received', text: `Additional acquisition: ${source} · ${campaignId}` }] })) form.reset(); }}><h3 className="font-medium text-ink">Add source / campaign</h3><Field label="Source"><select name="source" className={input}>{SOURCES.map(s => <option key={s}>{s}</option>)}</select></Field><Field label="Campaign ID"><input name="campaign" className={input} /></Field><Field label="Cost per lead (optional)"><input name="cost" type="number" min="0" step="0.01" className={input} /></Field><button className={button}>Add acquisition</button></form>
      </section>
    </div><div className="space-y-6">
      <section className={card}><h2 className="text-lg font-semibold text-ink">Follow-ups</h2>{lead.followups.length ? lead.followups.map(f => <div key={f.id} className="mt-3 rounded-lg bg-inset p-3 text-sm text-ink"><p>{dateLabel(f.due)} · {f.completedAt ? 'Completed' : 'Pending'}</p><p className="my-2 text-ink-2">{f.note}</p>{!f.completedAt && <button className={button} onClick={() => update({ ...lead, followups: lead.followups.map(x => x.id === f.id ? { ...x, completedAt: nowLocal() } : x), interactions: [...lead.interactions, { id: uid(), at: nowLocal(), type: 'followup', text: `Follow-up completed: ${f.note}` }] })}>Mark completed</button>}</div>) : <p className="mt-3 text-sm text-ink-muted">No follow-ups scheduled.</p>}</section>
      <section className={card}><h2 className="text-lg font-semibold text-ink">Interaction timeline</h2><p className="mt-1 text-xs text-ink-muted">Acquisition, calls, notes, follow-ups, store visits, and purchases · IST</p><ol className="mt-5 space-y-5 border-l border-line pl-5">{timeline.map(i => <li key={i.id}><p className="text-xs text-ink-muted">{dateLabel(i.at)}</p><h3 className="mt-1 text-sm font-semibold capitalize text-ink">{i.title}</h3><p className="mt-1 whitespace-pre-wrap text-sm text-ink-2">{i.text}</p></li>)}</ol></section>
      <section className={card}><h2 className="text-lg font-semibold text-ink">Sales & bills</h2><p className="mt-1 text-xs text-ink-muted">All locally imported purchases matching this phone number.</p>{sales.length ? sales.map(s => <div key={s.invoice} className="mt-3 flex flex-wrap justify-between gap-3 border-t border-line pt-3 text-sm text-ink"><div><p>{s.invoice}</p><p className="text-xs text-ink-2">{dateLabel(s.date)} · {s.store || 'Unknown store'}</p></div><p>{s.amount === null ? 'Amount not recorded' : money(s.amount)}</p></div>) : <p className="mt-3 text-sm text-ink-muted">No matching purchases yet.</p>}</section>
    </div></div>
  </main>;
}
