'use client';

import Link from 'next/link';
import { useMemo, useState } from 'react';
import { formatCurrency, formatCurrencyCompact, formatNumber } from '@/lib/format';
import type { DemandRow, PurchaseOrderRow, VendorWorkspaceRow } from '@/lib/queries/vendor-workspace';
import { VendorAdminHub } from '@/components/vendor-admin-hub';

const scoreTone = (score: number) => score >= 85 ? 'bg-status-good/10 text-status-good' : score >= 70 ? 'bg-accent-soft text-accent-strong' : 'bg-status-critical/10 text-status-critical';

export function VendorDashboard({ vendors: vendorData, demand, purchaseOrders }: { vendors: VendorWorkspaceRow[]; demand: DemandRow[]; purchaseOrders: PurchaseOrderRow[] }) {
  const totals = useMemo(() => vendorData.reduce((a, v) => ({ purchased: a.purchased + v.purchasedValue, sold: a.sold + v.soldValue, stock: a.stock + v.stockValue, overdue: a.overdue + v.overdue }), { purchased: 0, sold: 0, stock: 0, overdue: 0 }), [vendorData]);
  const [showAll, setShowAll] = useState(false);
  const vendors = showAll ? vendorData : vendorData.slice(0, 4);
  const demandLost = demand.reduce((sum, item) => sum + item.lost, 0);

  return <main className="mx-auto w-full max-w-[92rem] px-4 py-8 sm:px-6 lg:px-8">
    <header className="mb-6 flex flex-col justify-between gap-4 sm:flex-row sm:items-end">
      <div><div className="mb-2 inline-flex rounded-full bg-accent-soft px-2.5 py-1 text-xs font-semibold text-accent-strong">Vendor operations</div><h1 className="text-3xl font-semibold tracking-tight text-ink">Vendor intelligence</h1><p className="mt-1 max-w-[70ch] text-sm text-ink-2">One place for vendor performance, inventory health and the customer demand each supplier needs to serve.</p></div>
      <Link href="/vendor/vendors" className="rounded-xl bg-accent px-4 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-accent-strong">Open vendor master</Link>
    </header>
    <VendorAdminHub />
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
      <Metric label="Purchased value" value={formatCurrencyCompact(totals.purchased)} detail={`${formatNumber(vendorData.reduce((sum, v) => sum + v.purchasedQty, 0))} units purchased`} />
      <Metric label="Sold value" value={formatCurrencyCompact(totals.sold)} detail={`${totals.purchased ? ((totals.sold / totals.purchased) * 100).toFixed(1) : 0}% sell-through by value`} />
      <Metric label="Current stock value" value={formatCurrencyCompact(totals.stock)} detail={`${formatNumber(vendorData.reduce((sum, v) => sum + v.stockQty, 0))} units on hand`} />
      <Metric label="Overdue payable" value={formatCurrencyCompact(totals.overdue)} detail={`${vendorData.filter((v) => v.overdue > 0).length} vendors require attention`} critical />
    </div>
    <div className="mt-3 grid gap-3 xl:grid-cols-[1.55fr_1fr]">
      <section className="card rounded-2xl border border-line bg-surface p-5"><div className="flex items-start justify-between gap-4"><div><p className="text-[11px] font-bold uppercase tracking-[.09em] text-ink-muted">Vendor performance</p><h2 className="mt-1 text-lg font-semibold text-ink">Scorecard</h2></div><button onClick={() => setShowAll(!showAll)} className="text-sm font-medium text-accent hover:text-accent-strong">{showAll ? 'Show less' : 'View all'}</button></div><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[38rem] text-sm"><thead className="text-left text-[11px] font-bold uppercase tracking-[.08em] text-ink-muted"><tr><th className="pb-2">Vendor</th><th className="pb-2 text-right">Sell-through</th><th className="pb-2 text-right">Aging</th><th className="pb-2 text-right">Margin</th><th className="pb-2 text-right">Score</th></tr></thead><tbody>{vendors.map(v => <tr key={v.id} className="border-t border-grid"><td className="py-3"><p className="font-medium text-ink">{v.company}</p><p className="text-xs text-ink-muted">{v.categories.join(' · ')}</p></td><td className="tnum py-3 text-right text-ink-2">{((v.soldValue / v.purchasedValue) * 100).toFixed(0)}%</td><td className="tnum py-3 text-right text-ink-2">{v.agingDays} days</td><td className="tnum py-3 text-right text-ink-2">{v.marginPct}%</td><td className="py-3 text-right"><span className={`inline-flex rounded-full px-2.5 py-1 text-xs font-bold ${scoreTone(v.score)}`}>{v.score}/100</span></td></tr>)}</tbody></table></div></section>
      <section className="card rounded-2xl border border-line bg-surface p-5"><p className="text-[11px] font-bold uppercase tracking-[.09em] text-ink-muted">Customer demand</p><h2 className="mt-1 text-lg font-semibold text-ink">Demand at risk</h2><p className="mt-2 text-sm text-ink-2"><span className="font-semibold text-status-critical">{formatNumber(demandLost)} requests</span> could not be fully fulfilled this month.</p><div className="mt-4 space-y-3">{demand.filter(d => d.lost > 0).slice(0, 3).map(d => <div key={d.category} className="rounded-xl bg-inset p-3"><div className="flex justify-between gap-3"><div><p className="font-medium text-ink">{d.category}</p><p className="text-xs text-ink-2">{d.vendor}</p></div><p className="tnum text-sm font-semibold text-status-critical">{d.lost} lost</p></div><p className="mt-2 text-xs text-ink-muted">Potential revenue {formatCurrencyCompact(d.opportunity)}</p></div>)}</div><Link href="/vendor/demand" className="mt-5 inline-block text-sm font-medium text-accent hover:text-accent-strong">View demand analysis →</Link></section>
    </div>
    <div className="mt-3 grid gap-3 xl:grid-cols-2"><section className="card rounded-2xl border border-line bg-surface p-5"><p className="text-[11px] font-bold uppercase tracking-[.09em] text-ink-muted">Purchase operations</p><h2 className="mt-1 text-lg font-semibold text-ink">Recent purchase orders</h2><div className="mt-4 space-y-3">{purchaseOrders.map(po => <div key={po.po} className="flex items-center justify-between gap-3 border-t border-grid pt-3 first:border-0 first:pt-0"><div><p className="font-medium text-ink">{po.po} · {po.vendor}</p><p className="text-xs text-ink-2">{po.date} · {po.category}</p></div><div className="text-right"><p className="tnum font-medium text-ink">{formatCurrency(po.amount)}</p><p className="text-xs text-ink-muted">{po.status}</p></div></div>)}</div></section><section className="card rounded-2xl border border-line bg-surface p-5"><p className="text-[11px] font-bold uppercase tracking-[.09em] text-ink-muted">What needs action</p><h2 className="mt-1 text-lg font-semibold text-ink">Priority queue</h2><div className="mt-4 space-y-3 text-sm">{vendorData.filter(v => v.overdue > 0).slice(0, 3).map(v => <Action key={v.id} title={`Clear ${v.company} payment exception`} detail={`${formatCurrencyCompact(v.overdue)} is overdue; ${formatNumber(v.stockQty)} units remain in stock.`} />)}{demand.filter(d => d.lost > 0).slice(0, 1).map(d => <Action key={d.category} title={`Review ${d.category} replenishment`} detail={`${formatNumber(d.lost)} customer requests cannot yet be fulfilled.`} />)}</div></section></div>
  </main>;
}

export function VendorMaster({ vendors }: { vendors: VendorWorkspaceRow[] }) { const [query, setQuery] = useState(''); const rows = vendors.filter(v => `${v.company} ${v.brand} ${v.categories.join(' ')}`.toLowerCase().includes(query.toLowerCase())); return <main className="mx-auto w-full max-w-[92rem] px-4 py-8 sm:px-6 lg:px-8"><header className="mb-6 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.09em] text-accent">Vendor operations</p><h1 className="text-3xl font-semibold tracking-tight text-ink">Vendor master</h1><p className="mt-1 text-sm text-ink-2">Profiles, compliance details and the live commercial picture for every supplier.</p></div><Link href="/vendor" className="text-sm font-medium text-accent">← Dashboard</Link></header><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search vendor, brand or category" className="mb-4 w-full rounded-xl border border-line bg-surface px-4 py-3 text-sm text-ink outline-none placeholder:text-ink-muted focus:border-accent sm:max-w-md" /><section className="card overflow-x-auto rounded-2xl border border-line bg-surface"><table className="w-full min-w-[72rem] text-sm"><thead className="bg-inset text-left text-[11px] font-bold uppercase tracking-[.08em] text-ink-muted"><tr><th className="px-5 py-3">Vendor</th><th className="px-5 py-3">Contact & compliance</th><th className="px-5 py-3 text-right">Stock</th><th className="px-5 py-3 text-right">Payable</th><th className="px-5 py-3 text-right">Score</th></tr></thead><tbody>{rows.map(v => <tr key={v.id} className="border-t border-grid align-top"><td className="px-5 py-4"><p className="font-semibold text-ink">{v.company}</p><p className="text-xs text-ink-2">{v.id} · {v.brand}</p><p className="mt-1 text-xs text-ink-muted">{v.categories.join(', ')}</p></td><td className="px-5 py-4 text-ink-2"><p>{v.contact} · {v.phone}</p><p className="mt-1 text-xs text-ink-muted">{v.email}</p><p className="mt-1 text-xs text-ink-muted">{v.city}, {v.state} · GSTIN {v.gstin} · PAN {v.pan}</p></td><td className="tnum px-5 py-4 text-right"><p className="font-medium text-ink">{formatCurrencyCompact(v.stockValue)}</p><p className="text-xs text-ink-muted">{v.stockQty} units · {v.agingDays} days aging</p></td><td className="tnum px-5 py-4 text-right"><p className="font-medium text-ink">{formatCurrencyCompact(v.outstanding)}</p><p className={`text-xs ${v.overdue ? 'text-status-critical' : 'text-ink-muted'}`}>{v.overdue ? `${formatCurrencyCompact(v.overdue)} overdue` : 'On schedule'}</p></td><td className="px-5 py-4 text-right"><span className={`inline-flex rounded-full px-2.5 py-1 text-xs font-bold ${scoreTone(v.score)}`}>{v.score}/100</span></td></tr>)}</tbody></table></section></main>; }

export function CustomerDemand({ demand }: { demand: DemandRow[] }) { const requested = demand.reduce((sum, d) => sum + d.requested, 0); const fulfilled = demand.reduce((sum, d) => sum + d.fulfilled, 0); const opportunity = demand.reduce((sum, d) => sum + d.opportunity, 0); return <main className="mx-auto w-full max-w-[92rem] px-4 py-8 sm:px-6 lg:px-8"><header className="mb-6 flex items-end justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[.09em] text-accent">Customer → supplier connection</p><h1 className="text-3xl font-semibold tracking-tight text-ink">Customer demand → vendor supply</h1><p className="mt-1 max-w-[70ch] text-sm text-ink-2">Connect what customers asked for with the supplier and inventory position behind each category.</p></div><Link href="/vendor" className="text-sm font-medium text-accent">← Dashboard</Link></header><div className="grid gap-3 sm:grid-cols-3"><Metric label="Customer requests" value={formatNumber(requested)} detail={`Across ${demand.length} supplied categories`} /><Metric label="Fully fulfilled" value={formatNumber(fulfilled)} detail={`${requested ? ((fulfilled / requested) * 100).toFixed(1) : 0}% fulfilment rate`} /><Metric label="Revenue opportunity" value={formatCurrencyCompact(opportunity)} detail={`From ${formatNumber(requested - fulfilled)} unfulfilled requests`} critical /></div><section className="card mt-3 overflow-x-auto rounded-2xl border border-line bg-surface"><table className="w-full min-w-[52rem] text-sm"><thead className="bg-inset text-left text-[11px] font-bold uppercase tracking-[.08em] text-ink-muted"><tr><th className="px-5 py-3">Customer demand</th><th className="px-5 py-3">Mapped vendor</th><th className="px-5 py-3 text-right">Fulfilment</th><th className="px-5 py-3 text-right">Lost demand</th><th className="px-5 py-3 text-right">Opportunity</th></tr></thead><tbody>{demand.map(d => <tr key={d.category} className="border-t border-grid"><td className="px-5 py-4"><p className="font-semibold text-ink">{d.category}</p><p className="text-xs text-ink-muted">{d.requested} customer requests</p></td><td className="px-5 py-4"><p className="text-ink">{d.vendor}</p><p className={`mt-1 text-xs ${d.availability === 'Available' ? 'text-status-good' : 'text-status-critical'}`}>{d.availability}</p></td><td className="tnum px-5 py-4 text-right text-ink">{d.fulfilled}/{d.requested} <span className="text-ink-muted">({((d.fulfilled / d.requested) * 100).toFixed(0)}%)</span></td><td className="tnum px-5 py-4 text-right font-medium text-status-critical">{d.lost}</td><td className="tnum px-5 py-4 text-right font-semibold text-ink">{formatCurrency(d.opportunity)}</td></tr>)}</tbody></table></section><p className="mt-4 text-xs text-ink-muted">Demand rows are linked to a vendor and may also carry a canonical CRM customer ID; customer identities remain owned by the CRM.</p></main>; }

function Metric({ label, value, detail, critical = false }: { label: string; value: string; detail: string; critical?: boolean }) { return <section className="card rounded-2xl border border-line bg-surface p-5"><p className="text-[11px] font-bold uppercase tracking-[.09em] text-ink-muted">{label}</p><p className={`mt-2 text-2xl font-semibold tracking-tight ${critical ? 'text-status-critical' : 'text-ink'}`}>{value}</p><p className="mt-1 text-xs text-ink-2">{detail}</p></section>; }
function Action({ title, detail }: { title: string; detail: string }) { return <div className="rounded-xl bg-inset p-3"><p className="font-medium text-ink">{title}</p><p className="mt-1 text-xs leading-5 text-ink-2">{detail}</p></div>; }
