'use client';

import Link from 'next/link';
import { useMemo, useState } from 'react';
import { formatCurrencyCompact, formatNumber } from '@/lib/format';
import type { VendorWorkspaceRow } from '@/lib/queries/vendor-workspace';

export function VendorMasterDirectory({ vendors }: { vendors: VendorWorkspaceRow[] }) {
  const [query, setQuery] = useState('');
  const rows = useMemo(() => vendors.filter((vendor) => `${vendor.company} ${vendor.brand} ${vendor.categories.join(' ')} ${vendor.city}`.toLowerCase().includes(query.toLowerCase())), [query, vendors]);
  return <main className="mx-auto w-full max-w-[92rem] px-4 py-8 sm:px-6 lg:px-8"><header className="mb-6 flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.09em] text-accent">Step 1 · supplier setup</p><h1 className="text-3xl font-semibold tracking-tight text-ink">Vendor master</h1><p className="mt-1 max-w-[65ch] text-sm text-ink-2">A complete supplier directory. Contact, address, compliance, category and current commercial position stay together.</p></div><Link href="/vendor" className="text-sm font-medium text-accent">← Operations overview</Link></header><div className="mb-4 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search vendor, brand, category or city" className="w-full rounded-xl border border-line bg-surface px-4 py-3 text-sm text-ink outline-none placeholder:text-ink-muted focus:border-accent sm:max-w-md" /><p className="tnum text-xs text-ink-muted">{formatNumber(rows.length)} of {formatNumber(vendors.length)} vendors shown</p></div><div className="grid gap-4 lg:grid-cols-2">{rows.map((vendor) => <article key={vendor.id} className="card rounded-2xl border border-line bg-surface p-5"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-semibold text-accent">{vendor.id}</p><h2 className="mt-1 text-lg font-semibold text-ink">{vendor.company}</h2><p className="text-sm text-ink-2">{vendor.brand} · {vendor.categories.join(', ')}</p></div><span className="rounded-full bg-accent-soft px-2.5 py-1 text-xs font-bold text-accent-strong">Score {vendor.score}</span></div><div className="mt-4 grid gap-3 border-t border-grid pt-4 sm:grid-cols-2"><Field label="Contact" value={`${vendor.contact} · ${vendor.phone}`} /><Field label="Email" value={vendor.email} /><Field label="Address" value={`${vendor.address}, ${vendor.city}, ${vendor.state}`} /><Field label="Compliance" value={`GSTIN ${vendor.gstin} · PAN ${vendor.pan}`} /></div><div className="mt-4 grid grid-cols-3 gap-2 rounded-xl bg-inset p-3 text-center"><Metric label="Stock" value={formatCurrencyCompact(vendor.stockValue)} /><Metric label="Payable" value={formatCurrencyCompact(vendor.outstanding)} /><Metric label="Overdue" value={formatCurrencyCompact(vendor.overdue)} critical={vendor.overdue > 0} /></div></article>)}</div></main>;
}
function Field({ label, value }: { label: string; value: string }) { return <div><p className="text-[10px] font-bold uppercase tracking-[.08em] text-ink-muted">{label}</p><p className="mt-1 break-words text-sm text-ink-2">{value}</p></div>; }
function Metric({ label, value, critical = false }: { label: string; value: string; critical?: boolean }) { return <div><p className="text-[10px] font-bold uppercase tracking-[.08em] text-ink-muted">{label}</p><p className={`mt-1 text-sm font-semibold ${critical ? 'text-status-critical' : 'text-ink'}`}>{value}</p></div>; }
